/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 214 "/usr/lib/gcc/i486-linux-gnu/4.1.3/include/stddef.h"
typedef unsigned int size_t;
#line 59 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 144 "/usr/include/bits/types.h"
typedef long __off_t;
#line 145 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 45
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 167 "/usr/include/libio.h"
struct _IO_FILE;
#line 177 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 183 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 268 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15U * sizeof(int ) - 4U * sizeof(void *)) - sizeof(size_t )] ;
};
#line 214 "/usr/include/stdio.h"
extern int fclose(FILE *__stream ) ;
#line 249
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 337
extern int printf(char const   * __restrict  __format  , ...) ;
#line 445
extern int fgetc(FILE *__stream ) ;
#line 7 "wc.c"
void DYTAN_tag(void *addr , size_t size , char *name ) 
{ 

  {
#line 7
  return;
}
}
#line 8 "wc.c"
void DYTAN_display(void *addr , size_t size , char *fmt  , ...) 
{ 

  {
#line 8
  return;
}
}
#line 10 "wc.c"
int main(int argc , char **argv ) 
{ char c ;
  int i ;
  int count ;
  int total_count ;
  FILE *fp ;
  int tmp ;
  int tmp___0 ;

  {
#line 18
  total_count = 0;
#line 20
  i = 1;
#line 20
  while (i < argc) {
#line 22
    count = 0;
#line 24
    fp = fopen((char const   * __restrict  )*(argv + i), (char const   * __restrict  )"r");
#line 26
    tmp = fgetc(fp);
#line 26
    c = (char )tmp;
#line 27
    DYTAN_tag((void *)(& c), sizeof(c), *(argv + i));
#line 29
    while ((int )c != -1) {
#line 30
      if ((int )c == 10) {
#line 30
        count ++;
      }
#line 32
      tmp___0 = fgetc(fp);
#line 32
      c = (char )tmp___0;
#line 33
      DYTAN_tag((void *)(& c), sizeof(c), *(argv + i));
    }
#line 35
    fclose(fp);
#line 37
    DYTAN_display((void *)(& count), sizeof(count), (char *)"count=%d", count);
#line 38
    printf((char const   * __restrict  )"%s: %d\n", *(argv + i), count);
#line 40
    total_count += count;
#line 20
    i ++;
  }
#line 43
  DYTAN_display((void *)(& total_count), sizeof(total_count), (char *)"total_count=%d",
                total_count);
#line 44
  printf((char const   * __restrict  )"Total: %d\n", total_count);
#line 46
  return (0);
}
}
